# Change these first
owner: intecom1980 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SRV INTECOM CLOUD
    check: "tcp-ping"
    url: https://srv.intecom.cloud
    port: 8080
  - name: S1 INTECOM CLOUD
    url: https://s1.intecom.cloud
  - name: UNIFI INTECOM
    check: "tcp-ping"
    url: https://unifi.intecom.cat
    port: 8443
  - name: Golf Mar 2
    check: "tcp-ping"
    url: http://84a107d35b90.sn.mynetname.net/
    port: 8291
  - name: GOLF RELAX
    check: "tcp-ping"
    url: a36a0c0ae39e.sn.mynetname.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.intecom.cloud
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status INTECOM
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: INTECOM
      href: https://intecom.cloud
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
